### ISSUE TITLE
Add ARTIK 710 to GPIO list

### ISSUE THREAD

**Issue by markrpw** [SenseTecnic/node-red-contrib-artik#1]
Your ARTIK nodes are really convenient! Samsung has released the ARTIK 710 as an intermediate product between the ARTIK 5 (now called 520) and ARTIK 10 (now called 1020). Any chance you could add the ARTIK 710 selection into your project? You'll find all the GPIO info you need here:

https://developer.artik.io/documentation/developer-guide/gpio/gpio-mapping.html

ARTIK 710 is interesting because it has two LEDs and two pushbuttons that are unassigned and available for user applications, so it'd be especially handy to have your nodes available for them.

Thanks in advance! -- Mark

**Comment by jmikerq** [comment]
hello mark, thanks for using our Artik node!

Currently we only have the artik 5 and artik 10 boards in the lab, so even if I write the nodes for artik 710, I wouldn't be able to fully test the code.

**Comment by markrpw** [comment]
Thanks for the reply!

After I wrote you this note, it turns out others in my team had already planned a meeting with Rodger, which I attended this past Monday. We will definitely get you guys an ARTIK 710 kit to try these nodes out. I will see how it was handled on the previous boards and get it underway.

If you want to try to put anything together in advance, I’d certainly be available to test out your nodes on our end. I’m finishing up a new tutorial that you’ll be able to see online sometime Thursday at https://developer.artik.io/documentation/artik/tutorials/node-red.html but it currently doesn’t have full support for ARTIK 710, which is our flagship product at this point. I’ll be anxious to update it with information for your new nodes as soon as they’re ready!

Mark

**Comment by rlea** [comment]
Hi Mark,

thanks for the update.

I'll chat to the engineer (Michael) tomorrow and update him on our meeting.
We'll take a look at the documentation and see what we can do.

If you could work on getting us a 710 kit (with sensors) that would be
really helpful,

cheers

rodger

**Comment by jmikerq** [comment]
@markrpw Hello Mark,

So I just pushed the new version in the develop branch that has the pin mappings for Artik 710. Can you check out if the new version works on your Artik 710 board? 

Thanks,
Michael

**Comment by markrpw** [comment]
Hi Michael,

I wanted to let you know that I’m testing now and so far, so good! I’ll give you a better update once I’ve got more done. By the way, thanks for changing the naming to our new scheme for the various products. It helps a lot!

Mark

**Comment by markrpw** [comment]
Hi again Michael,

I’ve got the remaining A710 testing results for you. Everything checks out fine. It might be best to remove the SW options from the Out node and the LED options from the In node, since it could confuse someone, but I’ll leave that as your call.

Whenever you get the chance to deploy the package, let me know and I’ll match our online instructions to it. At that time I’ll also put in a link to your FRED article for ARTIK at http://developers.sensetecnic.com/article/tutorial-controlling-an-artik-board-using-fred-and-node-red/ so that you can track interest.

Thanks very much for the rapid effort!

Regards,
Mark


From: /O=SAMSUNG SEMICONDUCTOR/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=MARK WILLIAMS-SSIF18 On Behalf Of Mark Williams
Sent: Monday, December 05, 2016 4:33 PM
To: 'SenseTecnic/node-red-contrib-artik'
Subject: RE: [SenseTecnic/node-red-contrib-artik] Add ARTIK 710 to GPIO list (#1)

Hi Michael,

I wanted to let you know that I’m testing now and so far, so good! I’ll give you a better update once I’ve got more done. By the way, thanks for changing the naming to our new scheme for the various products. It helps a lot!

Mark

**Comment by jmikerq** [comment]
that is a good call to the SW options and LED options @markrpw, I will fix that before publishing the new version.

Once that is done, I will let you know.

**Comment by jmikerq** [comment]
hello @markrpw, I've made the new update and published on npm now.

**Comment by markrpw** [comment]
Thanks, Michael! The new version of the articles should show up by the end of the day, or Monday if not

https://developer.artik.io/documentation/artik/tutorials/node-red.html
https://developer.artik.io/documentation/artik/tutorials/node-red-cloud.html

By the way, we’ve made a mention of the FRED nodes that you’ll find in the second article once the new version gets posted. Look at the “Extra Credit” section at the end of the article. I hope to find time soon to start using them in our other articles.

-- Mark
